### ISSUE TITLE
User reported that Darwin ARM64 artifact is damaged

### ISSUE THREAD

**Issue by ECRomaneli** [ECRomaneli/Handbook#1]
It seems as even though the artifact has been generated without apparent failure, the output is somehow not working in ARM Macs.

**Comment by ECRomaneli** [comment]
I will proceed and verify the build parameters and check for some similar issues reported for the `electron-forge`.

**Comment by ECRomaneli** [comment]
The build is now being done in the native OS with the right architecture. Need testers to verify the `.app`.

**Comment by ECRomaneli** [comment]
Even with the new build process, the error is still happening, I will try to replace the ARM64 version with a Universal one as a palliative fix for now.

**Comment by ECRomaneli** [comment]
Waiting for candidates to test the universal build.

**Comment by ecromaneli-trustly** [comment]
The user reported that the universal build worked. I will keep searching for other solutions as the universal build is not ideal due to its size 2x bigger.

**Comment by ECRomaneli** [comment]
The user reported that the universal build worked. I will keep searching for other solutions as the universal build is not ideal due to its size 2x bigger.

**Comment by ECRomaneli** [comment]
As the universal build is working, I am going to close this issue. However, I am going to proceed to find other approaches to avoid creating unnecessary files under the package.
